"""empty message

Revision ID: 9db77931c84e
Revises: First revision
Create Date: 2021-10-30 10:56:02.920834

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9db77931c84e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sellers_cpf"), "sellers", ["cpf"], unique=True)
    op.create_table(
        "sales",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("status", sa.Enum("REFUSED", "APROVED", "PENDING", name="statusenum"), nullable=False),
        sa.Column("seller_cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_cpf"],
            ["sellers.cpf"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_date"), "sales", ["date"], unique=False)
    op.create_index(op.f("ix_sales_seller_cpf"), "sales", ["seller_cpf"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_seller_cpf"), table_name="sales")
    op.drop_index(op.f("ix_sales_date"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_sellers_cpf"), table_name="sellers")
    op.drop_table("sellers")
    # ### end Alembic commands ###
